language: elixir
elixir:
  - 1.6
otp_release:
  - 20.1
addons:
  apt:
    packages:
      - cargo
sudo: false
before_cache:
  - rm -r _build/dev/lib/overdiscord deps/certifi/.rebar3/erlcinfo
cache:
  directories:
    - deps
    - _build
    - $HOME/.cargo
    - $HOME/.hex
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
before_script:
  - mix deps.get
  - mix deps.compile
script:
  - mix compile # test
  - mix format --check-formatted
  - mix inch.report
after_script:
  - echo Complete
notifications:
  recipients:
    - overminddl1@gmail.com
